CREATE DATABASE LIBRARYDB;

USE LIBRARYDB;

DROP TABLE BOOKS;

CREATE TABLE IF NOT EXISTS BOOKS (
	id				CHAR(36)		PRIMARY KEY,
    name 			VARCHAR(60) 	NOT NULL,
    description		VARCHAR(200)	NOT NULL,
    price			Float			NOT NULL,
    author			VARCHAR(30)		NOT NULL
);

SELECT * FROM BOOKS;